### ISSUE TITLE
File import via ctkDICOMIndexer seems to copy always 

### ISSUE THREAD

**Issue by nolden** [commontk/CTK#104]
It should not copy by default, only if the user selected the copy option in the import dialog of ctkDICOMAppWidget (or something similar in an application)

**Comment by jcfr** [comment]
@pieper @nolden @fedorov @lassoan  @nolden 

Considering the issue is quite hold and the DICOM infrastructure in DCMTK, CTK and Slicer  went through a lot of improvements, I am closing this issue.

Please, if you think the issue is still current, consider opening a new issue (referencing this one if it is relevant)
