### ISSUE TITLE
Is there any guide for compiling CTK?

### ISSUE THREAD

**Issue by hheehhaa** [commontk/CTK#1141]
Dear: 
       it is difficult to build CTK, and the CMakeLists in CTK project are so complex that it is diffcult for beginner to understand and make revision. 
      could you please provide an reference about how to use CMake-gui.exe and MinGW to build CTK project?
      Greate Thanks!

**Comment by pieper** [comment]
CTK has a lot of complex options, so there's not always an easy way to build it.  Plus MinGW has some non-standard features so I'm not sure CTK has ever been built on it.  We do target the windows native build tools though and you might be able to build with those and use the results in MinGW.  You can check how [CTK is used in Slicer](https://github.com/Slicer/Slicer/blob/main/SuperBuild/External_CTK.cmake) for build configurations that are known to work across OSes (of course, that's even more complex than CTK itself).

**Comment by lassoan** [comment]
The idea of MinGW was to create multi-platform libraries by porting the Linux toolchain to Windows, but it never worked well (based on my experience it introduced as many problems as it solved). It has been made largely irrelevant by CMake, which allows developers to write multi-platform code that can be built on each platform by native toolsets.

I would recommend to use Visual Studio on Windows also because then if you have any specific questions you can ask us here.

**Comment by hheehhaa** [comment]
OK，Thanks, i got it. i will have a try at Visual Studio.
