### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by XXOO9** [commontk/CTK#1146]
i meet a problem when i compile CTK with CMake-gui, my configuration shows below( Qt 5.9.6  win10   msvc2015_64 ):
![image](https://github.com/commontk/CTK/assets/75569891/fba0c860-bf52-4ff7-9437-e1362d8cedd4)

after i pressed Configure button, as screen capture shows,  there is no sql module required, but when i compiled the solution generated by CMake-gui, an compile error happend
![image](https://github.com/commontk/CTK/assets/75569891/25870819-52f2-4b37-a45b-d9c4422e500a)

some one help me, please!

**Comment by jcfr** [comment]
Enabling `CTK_ENABLE_PluginFramework` is expected to require the `Sql` Qt module.

Inspecting the code:

https://github.com/commontk/CTK/blob/b9ef9b8aa1938676ce0ac105a3deb0e1bfc235a1/CMake/ctkMacroSetupQt.cmake#L62-L67

... revealed that the test was using `Libs/PluginFramework` instead of `CTK_LIB_PluginFramework` which may explain what you are observing.
